Se estimará $\pi=\theta=\int_0^1f(x)dx=\int_0^1\frac{4}{1+x^2}dx$ utilizando muestreo de importancia y $g(x)=\frac{2(2-x}{3}\;, 0<x<1$, como densidad instrumental.
<<g(x)>>=
@
<<f(x)>>=
@
Para obtener la gráfica de $f(x)$ y $g(x)$ en la Figura~\ref{fig:Plotgf}, primero se genera un vector con el soporte de ambas funciones.
<<Soporte>>=
@
<<Plotgf, fig.cap="Digrama de las funciones $f(x)$ y $g(x)$ (instrumental).">>=
@
